// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymbFJWEDR4q8IavXcL7gr0DvNcD36VFE',
    appId: '1:483814936147:web:27df58619b58aaadfb00a6',
    messagingSenderId: '483814936147',
    projectId: 'fixitservice-41067',
    authDomain: 'fixitservice-41067.firebaseapp.com',
    storageBucket: 'fixitservice-41067.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHg3LlF_9_XAU64zeT6WV4FOh6OJdo24',
    appId: '1:483814936147:android:0d8cc1d703f6e668fb00a6',
    messagingSenderId: '483814936147',
    projectId: 'fixitservice-41067',
    storageBucket: 'fixitservice-41067.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1JSE-51JcQPrH32E1wAyjx0TkQJNNko',
    appId: '1:483814936147:ios:cf88ea879667257afb00a6',
    messagingSenderId: '483814936147',
    projectId: 'fixitservice-41067',
    storageBucket: 'fixitservice-41067.firebasestorage.app',
    iosClientId: '483814936147-4c57c1ut3a31mtoijplmb8440ra6e3j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitService',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ1JSE-51JcQPrH32E1wAyjx0TkQJNNko',
    appId: '1:483814936147:ios:cf88ea879667257afb00a6',
    messagingSenderId: '483814936147',
    projectId: 'fixitservice-41067',
    storageBucket: 'fixitservice-41067.firebasestorage.app',
    iosClientId: '483814936147-4c57c1ut3a31mtoijplmb8440ra6e3j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBymbFJWEDR4q8IavXcL7gr0DvNcD36VFE',
    appId: '1:483814936147:web:27df58619b58aaadfb00a6',
    messagingSenderId: '483814936147',
    projectId: 'fixitservice-41067',
    authDomain: 'fixitservice-41067.firebaseapp.com',
    storageBucket: 'fixitservice-41067.firebasestorage.app',
  );
}
