// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnqdVPV4kOeVSP7S0QVoU--fTd39kXqao',
    appId: '1:985453165115:web:97e485b125c3bf94653a1e',
    messagingSenderId: '985453165115',
    projectId: 'fixitservices-9d811',
    authDomain: 'fixitservices-9d811.firebaseapp.com',
    storageBucket: 'fixitservices-9d811.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZoWA6qaZOmMEUDhSCXIKld91LMbXNno',
    appId: '1:985453165115:android:113ad53c8622da34653a1e',
    messagingSenderId: '985453165115',
    projectId: 'fixitservices-9d811',
    storageBucket: 'fixitservices-9d811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAId454RTtb6cxnahIbP3FjbAh2lxF8Qms',
    appId: '1:985453165115:ios:2b64b423d97d51ee653a1e',
    messagingSenderId: '985453165115',
    projectId: 'fixitservices-9d811',
    storageBucket: 'fixitservices-9d811.firebasestorage.app',
    iosClientId: '985453165115-f5sbtspkcg6m8svnbpkv8epaogmltdk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAId454RTtb6cxnahIbP3FjbAh2lxF8Qms',
    appId: '1:985453165115:ios:2b64b423d97d51ee653a1e',
    messagingSenderId: '985453165115',
    projectId: 'fixitservices-9d811',
    storageBucket: 'fixitservices-9d811.firebasestorage.app',
    iosClientId: '985453165115-f5sbtspkcg6m8svnbpkv8epaogmltdk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnqdVPV4kOeVSP7S0QVoU--fTd39kXqao',
    appId: '1:985453165115:web:65d022190c3cdf71653a1e',
    messagingSenderId: '985453165115',
    projectId: 'fixitservices-9d811',
    authDomain: 'fixitservices-9d811.firebaseapp.com',
    storageBucket: 'fixitservices-9d811.firebasestorage.app',
  );
}
